name: vimflowy
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
      env:
        RUNNER_TEMP: "/tmp/"

    - run: npm install
    - run: npm install mocha ts-node tslint typescript@3.1.6

    - run: npm run build
    - run: npm run verify

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: phaze9/vimflowy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
