name: vimflowy
on:   push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: phaze9/vimflowy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
